### ISSUE TITLE
Possible bug in symmetrization

### ISSUE THREAD

**Issue by DavidMStraub** [DsixTools/DsixTools#1]
Hi all,

as discussed in https://github.com/DsixTools/python-smeftrunner/issues/9, I need to implement the symmetrization of input values in python-smeftrunner. I did that now (https://github.com/DsixTools/python-smeftrunner/commit/fe26906fa2ed846aeccdd7967d1675e90f736ee0), basically copying @avelino3000's code from `input.m`. I then added extensive [unit tests](https://github.com/DsixTools/python-smeftrunner/blob/master/smeftrunner/tests/test_def.py) to make sure the resulting tensors have the right symmetry properties. This worked for class 2, 4, 5, 7, and 9 operators. However it fails for class 6 and 8.

Before trying to fix it, it would be good if you can confirm this is a bug, then we can fix it together.

Focusing for the moment on class 6 - this is the special case of Q<sub>ee</sub> - I find for instance that

- 1231 != 3112
- 2231 != 3122
- 2331 != 3123

I also have a suspicion what the problem is. If you look at the [code for category 4](https://github.com/DsixTools/DsixTools/blob/master/DsixTools/input.m#L240-L293), you can check that none of the elements appear both on the LHS and on the RHS of the equations.

But if you look at [category 6](https://github.com/DsixTools/DsixTools/blob/master/DsixTools/input.m#L448-L507), you will see that there are three elements (3211, 3221, 3321) that appear both on the LHS and RHS of the equations. This does not seem to make sense to me and indeed I think this is what screws up the symmetry.

**Comment by avelino3000** [comment]
Thanks David, you were completely right. I spotted a little typo in the notebook that I used to generate those symmetry relations. Now [category 6](https://github.com/DsixTools/DsixTools/blob/master/DsixTools/input.m#L448-L507) should be fixed. However, I had a look at the analogous code for [category 8](https://github.com/DsixTools/DsixTools/blob/master/DsixTools/input.m#L607-L630) but could not find anything weird. Did you find anything wrong there as well?

**Comment by DavidMStraub** [comment]
Great, that solves it indeed for cat 6!

The problem I have with cat 8 is that I'm trying to reproduce this identity

![screenshot_20170922_143026](https://user-images.githubusercontent.com/10965193/30744510-a790ee08-9fa2-11e7-8e9b-89cd3b4dac90.png)

from [this paper](https://arxiv.org/pdf/1405.0486.pdf) in [this test](https://github.com/DsixTools/python-smeftrunner/blob/ab0e1f7f915583f2d5289ece9569e838dd7b7c53/smeftrunner/tests/test_def.py#L65-L68) and it fails pretty badly. Haven't found a clue what could be the reason.

**Comment by celis** [comment]
Hi, 

maybe the last term on the test  you made for category 8 needs a minus sign  (in the print command, + v.transpose((2, 1, 0, 3) ->  - v.transpose((2, 1, 0, 3))

**Comment by DavidMStraub** [comment]
Well, I reimplemented this identity in Mathematica and obtained exactly the same relation as in your code. So it looks as I screwed up in the test. Stand by ...

**Comment by DavidMStraub** [comment]
Prblem solved! (a9bc78c2a9b4cbd9d9b222d653d6f64ab167bb0e)

So the cat 8 symmetrization in your code was correct, I just had a mistake in my use of `numpy.transpose` in the unit test.
